Set up the repository and move stuff from apify-sdk and apify-client here
apify/apify-shared-python pull request #2
Opened 2023-07-21 12:18 UTC by vdusek

I separated the PR into 3 commits. At first, I just copied the `apify-client-python` repository, and in the next commits, I did the changes to be able to see the changes I made.

Basically regarding the project setup I just removed the docs & test stuff.

The content of src was discussed on Slack with @fnesveda .

Closes #1.

2023-07-21 13:15 UTC, fnesveda requested changes
Cool! Just some small notes.

And you should also copy the unit tests from https://github.com/apify/apify-sdk-python/blob/master/tests/unit/test_utils.py and https://github.com/apify/apify-sdk-python/blob/master/tests/unit/test_consts.py to here.

2023-07-21 13:15 UTC, fnesveda commented on Makefile
> +
This package won't have any integration tests, so no need for this argument
```suggestion
```

2023-07-21 13:15 UTC, fnesveda commented on pyproject.toml
> +]
This package doesn't use `httpx` anywhere, no need for this
```suggestion
```

2023-07-24 09:55 UTC, vdusek commented
Thanks, @fnesveda. I fixed the minor issues you mentioned, added unit tests, and also a few lines into README.

2023-07-24 13:39 UTC, fnesveda requested changes
Looks good, last few tiny things I noticed, and then I think it's good to go.

2023-07-24 13:39 UTC, fnesveda commented on .flake8
> +    ./src/*.py,
Linting of tests won't work without this:
```suggestion
filename =
    ./scripts/*.py,
    ./src/*.py,
    ./tests/*.py
```

2023-07-24 13:39 UTC, fnesveda commented on tests/unit/test_consts.py
> +class TestConsts:  # noqa: D101
This `noqa` is not needed (I wonder why `flake8-noqa` didn't report it...)
```suggestion
class TestConsts:
```

2023-07-24 13:39 UTC, fnesveda commented on src/apify_shared/utils.py
> +def filter_out_none_values_recursively_internal(
I think this method could be prefixed with `_`, to make it explicit that it's private and internal.

2023-07-24 14:49 UTC, vdusek commented
Thanks, @fnesveda, it should be fixed now.

2023-07-24 16:52 UTC, merged